# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a9cf9432464fe85cb4f218da4987c5b0a708797a17cf7433b38002ef52bf2924378cf99961826a36fa40627ed02e1fb1ed087b7718b1ce29166f4f908b7385ac

test:
  secret_key_base: f0afc6c90426e58cb6b9c760e813972d509f893c57806570a11a0aeeacc4a646ee4da32c77e20e027a1b2c77e3a909d8a599fc153f4849855aab9aaef8b8eded

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
